fix -std=c23 build failure
gcc-15 switched to -std=c23 by default:

    https://gcc.gnu.org/git/?p=gcc.git;a=commitdiff;h=55e3bd376b2214e200fa76d12b67ff259b06c212

As a result `mumudvb` fails the build so only typedef int bool
for __STDC_VERSION__ <= 201710L (C17)

    ../../src/mumudvb.h:136:47: error: expected ';', identifier or '(' before 'bool'
      136 |     typedef enum { false = 0, true = !false } bool;
          |                                               ^~~~

Signed-off-by: Rudi Heitbaum <rudi@heitbaum.com>